name: genai-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
      - langchain
      - openai
      - langchain-community
      - yt_dlp
      - pypdf
      - tiktoken
      - streamlit
      - beautifulsoup4 # For web scraping (if needed)
      - requests # For web scraping (if needed)
      # - chromadb # or another vector database
      - recipe-scrapers
      - flask
      - bs4
      - FAIS
      - lark
      - docarray
      - panel 
